version: "2.1" 

services: 
  sonarr: 
    image: ghcr.io/linuxserver/sonarr 
    container_name: sonarr 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London 
      - UMASK_SET=022 #optional 
    volumes:
      - /media/SmallSlave/docker/sonarr/config:/config 
      - /media/BigSlave/TV:/tv/new
      - /media/Slave/TV:/tv/old
      - /media/BigSlave/Downloads:/downloads
    ports: 
      - 8989:8989
    restart: unless-stopped 
    #networks:
    #  - openvpn_openvpn-client
    network_mode: host

networks:
  openvpn_openvpn-client:
    external: true
