version: "2.1" 

services: 
  code-server: 
    image: ghcr.io/linuxserver/code-server 
    container_name: code-server 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London 
      - PASSWORD=password 
      - SUDO_PASSWORD=password
    volumes: 
      - /media/SmallSlave/docker/vscode/config:/config 
      - /media/SmallSlave/Users:/home
      - /media/SmallSlave/docker:/config/docker
      - /home/server/.ssh:/config/.ssh
    ports: 
      - 8443:8443
    restart: unless-stopped
