version: "2.1" 

services: 
  nextcloud: 
    image: linuxserver/nextcloud 
    container_name: nextcloud 
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/London 
    volumes: 
      - /media/SmallSlave/docker/nextcloud_ext/appdata:/config 
      - /media/SmallSlave/docker/nextcloud_ext/data:/data
    ports: 
      - 8201:443
    restart: unless-stopped
